service: aws-waf-association

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

resources:
  Resources:

    MyWAFACL:
      Type: AWS::WAFv2::WebACL
      Properties:
        DefaultAction:
          Allow: {}
        Description: Application WAF
        Scope: REGIONAL
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: AppRules
          SampledRequestsEnabled: true
        Rules:
          - Action:
              Block: {}
            Name: RateLimit
            Priority: 0
            Statement:
              RateBasedStatement:
                AggregateKeyType: "IP"
                Limit: 100
            VisibilityConfig:
              CloudWatchMetricsEnabled: true
              MetricName: RateLimiter
              SampledRequestsEnabled: true

    MyWAFAssociation:
      DependsOn: MyWAFACL
      Type: AWS::WAFv2::WebACLAssociation
      Properties: 
        ResourceArn:
          !Sub 
            - arn:aws:apigateway:${AWS::Region}::/restapis/${ApiId}/stages/${self:provider.stage}
            - { ApiId: !ImportValue QldbApiGatewayDemo-restApiId }
        WebACLArn: !GetAtt MyWAFACL.Arn
